package com.formulae.chef.ui.components

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.ui.unit.dp
import com.formulae.chef.ui.theme.AppTypography
import com.formulae.chef.ui.theme.Terracotta600
import com.formulae.chef.ui.theme.TextPrimary
import com.formulae.chef.ui.theme.White

@Composable
fun LegalInfoDialog(onDismiss: () -> Unit) {
    AlertDialog(
        onDismissRequest = onDismiss,
        containerColor = White,
        shape = RoundedCornerShape(8.dp),
        title = {
            Text(
                text = "Privacy & AI content",
                style = AppTypography.headlineLarge.copy(color = TextPrimary)
            )
        },
        text = {
            Text(
                text = "Beta privacy notice: Chef stores your email, chat messages, and saved " +
                    "recipes in Firebase to provide the app's features. We don't sell your data " +
                    "to third parties. Contact us to request deletion of your data.\n\n" +
                    "AI-generated content: Recipes, tips, and chat responses are generated by AI " +
                    "and may contain mistakes, including incorrect cooking times or temperatures. " +
                    "Always use your own judgment for food safety.",
                style = AppTypography.bodyMedium.copy(color = TextPrimary)
            )
        },
        confirmButton = {
            TextButton(
                onClick = onDismiss,
                colors = ButtonDefaults.textButtonColors(contentColor = Terracotta600)
            ) {
                Text("OK", style = AppTypography.labelLarge)
            }
        }
    )
}
