package com.formulae.chef.ui.components

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Close
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import com.formulae.chef.ui.theme.AppTypography
import com.formulae.chef.ui.theme.TextPrimary
import com.formulae.chef.ui.theme.White

@Composable
fun LegalInfoDialog(onDismiss: () -> Unit) {
    Dialog(onDismissRequest = onDismiss) {
        Surface(
            color = White,
            shape = RoundedCornerShape(8.dp),
            modifier = Modifier.fillMaxWidth()
        ) {
            // Equal padding on all sides; the X in the header replaces the old bottom
            // confirm button, so the dialog hugs its text.
            Column(modifier = Modifier.padding(24.dp)) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Text(
                        text = "Privacy & AI content",
                        style = AppTypography.headlineLarge.copy(color = TextPrimary),
                        modifier = Modifier.weight(1f)
                    )
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.Default.Close, contentDescription = "Close", tint = TextPrimary)
                    }
                }
                Spacer(modifier = Modifier.height(16.dp))
                Text(
                    text = "Beta privacy notice: Chef stores your email, chat messages, and saved " +
                        "recipes in Firebase to provide the app's features. We don't sell your data " +
                        "to third parties. Contact us to request deletion of your data.\n\n" +
                        "AI-generated content: Recipes, tips, and chat responses are generated by AI " +
                        "and may contain mistakes, including incorrect cooking times or temperatures. " +
                        "Always use your own judgment for food safety.",
                    style = AppTypography.bodyMedium.copy(color = TextPrimary)
                )
            }
        }
    }
}
